# P9: Reduce the Dimensionality of Sparse Feature Matrix

## Aim

Write a program for reducing the dimensionality of a sparse feature matrix.

## Objective

To reduce a high-dimensional sparse feature matrix into a lower-dimensional
representation while preserving the important information in the data.

## Technique Used

Truncated Singular Value Decomposition (Truncated SVD) is used for dimensionality
reduction of the sparse feature matrix.

## Libraries Used

- NumPy
- SciPy
- Scikit-learn

## Theory

A sparse feature matrix is a matrix in which most of the values are zero.

Sparse matrices are commonly generated in Machine Learning when dealing with
text data, categorical features, one-hot encoding, and document-term matrices.

Reducing the dimensionality of a sparse matrix helps to:

- Reduce the number of features.
- Reduce memory usage.
- Improve computational efficiency.
- Remove redundant information.
- Make Machine Learning models faster.

For sparse matrices, **Truncated SVD** is commonly used because it can work
directly with sparse data.

The dimensionality reduction process is:

**Sparse Feature Matrix → Truncated SVD → Reduced Feature Matrix**

In [1]:
# Import required libraries

import numpy as np
from scipy.sparse import csr_matrix
from sklearn.decomposition import TruncatedSVD

## Step 1: Create the Feature Matrix

We create a feature matrix containing many zero values.

This represents a sparse feature matrix where only a small number of
features are present for each observation.

In [2]:
# Create a sample feature matrix
X = np.array([
    [1, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 1, 0],
    [1, 0, 1, 0, 0, 0],
    [0, 1, 0, 0, 1, 1],
    [1, 0, 1, 0, 0, 0]
])

# Display the original feature matrix
print("========== ORIGINAL FEATURE MATRIX ==========")
print(X)

# Display the shape of the matrix
print("\nOriginal Shape:", X.shape)

========== ORIGINAL FEATURE MATRIX ==========
[[1 0 0 1 0 0]
 [0 1 0 0 1 0]
 [1 0 1 0 0 0]
 [0 1 0 0 1 1]
 [1 0 1 0 0 0]]

Original Shape: (5, 6)


## Step 2: Convert the Matrix into Sparse Format

The NumPy matrix is converted into Compressed Sparse Row (CSR) format.

CSR stores the non-zero elements efficiently instead of storing every zero
value explicitly.

In [3]:
# Convert the feature matrix into a sparse CSR matrix
X_sparse = csr_matrix(X)

# Display the sparse matrix
print("========== SPARSE FEATURE MATRIX ==========")
print(X_sparse)

# Display the shape of the sparse matrix
print("\nSparse Matrix Shape:", X_sparse.shape)

# Display the number of non-zero elements
print("Number of Non-Zero Elements:", X_sparse.nnz)

========== SPARSE FEATURE MATRIX ==========
  (0, 0)	1
  (0, 3)	1
  (1, 1)	1
  (1, 4)	1
  (2, 0)	1
  (2, 2)	1
  (3, 1)	1
  (3, 4)	1
  (3, 5)	1
  (4, 0)	1
  (4, 2)	1

Sparse Matrix Shape: (5, 6)
Number of Non-Zero Elements: 11


## Step 3: Apply Truncated SVD

Truncated SVD is used to reduce the number of dimensions.

The original matrix contains **6 features**.

We will reduce these 6 features to **2 dimensions**.

`n_components=2` specifies that the reduced feature matrix should contain
2 dimensions.

In [4]:
# Create the Truncated SVD model
svd = TruncatedSVD(
    n_components=2,
    random_state=42
)

# Fit the model and transform the sparse matrix
X_reduced = svd.fit_transform(X_sparse)

# Display the reduced matrix
print("========== REDUCED FEATURE MATRIX ==========")
print(X_reduced)

# Display the new shape
print("\nReduced Shape:", X_reduced.shape)

========== REDUCED FEATURE MATRIX ==========
[[ 1.00000000e+00 -7.61149866e-17]
 [-1.04459119e-15  1.31438460e+00]
 [ 1.36602540e+00  8.74123347e-16]
 [-1.24630605e-15  1.68343278e+00]
 [ 1.36602540e+00  8.74123347e-16]]

Reduced Shape: (5, 2)


## Step 4: Check Explained Variance

Explained variance tells us how much information from the original
feature matrix is represented by each reduced component.

The total explained variance is obtained by adding the explained
variance ratio of all selected components.

In [5]:
# Display explained variance ratio
print("========== EXPLAINED VARIANCE ==========")

print("Explained Variance Ratio:")
print(svd.explained_variance_ratio_)

# Calculate total explained variance
total_variance = svd.explained_variance_ratio_.sum()

print("\nTotal Explained Variance:", total_variance)

========== EXPLAINED VARIANCE ==========
Explained Variance Ratio:
[0.30412659 0.43190172]

Total Explained Variance: 0.7360283065137769


## Step 5: Display Final Result

The original sparse feature matrix had 6 dimensions.

After applying Truncated SVD, the matrix has only 2 dimensions.

Therefore:

**Original Dimensions = 6**

**Reduced Dimensions = 2**

This reduces the dimensionality while retaining important information
from the original sparse feature matrix.

In [6]:
# Display the final dimensionality reduction result

print("========== FINAL RESULT ==========")

print("Original Number of Features:", X.shape[1])
print("Reduced Number of Features:", X_reduced.shape[1])

print("\nOriginal Shape:", X.shape)
print("Reduced Shape:", X_reduced.shape)

print("\nDimensionality reduction completed successfully.")

========== FINAL RESULT ==========
Original Number of Features: 6
Reduced Number of Features: 2

Original Shape: (5, 6)
Reduced Shape: (5, 2)

Dimensionality reduction completed successfully.


## Conclusion

In this practical, a sparse feature matrix was created and converted into
CSR sparse format using SciPy.

Truncated SVD was then applied to reduce the dimensionality of the sparse
feature matrix from 6 dimensions to 2 dimensions.

Thus, dimensionality reduction of a sparse feature matrix was successfully
performed while retaining important information from the original data.